import type React from "react";

export const common = {
  analyticsPane: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    background: "var(--bg-panel)",
    padding: "28px 28px 32px",
  },
  analyticsHeader: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)", marginBottom: 4 },
  analyticsSubtitle: { fontSize: 12, color: "var(--text-muted)", marginBottom: 20 },
  heatmapRow: { display: "flex", gap: 8, alignItems: "flex-end", marginBottom: 4 },
  heatmapCell: {
    width: 26,
    height: 26,
    borderRadius: 6,
    border: "1px solid var(--border-dim)",
    transition: "transform 0.1s ease",
    cursor: "default",
  },
  heatmapLabel: {
    fontSize: 10,
    color: "var(--text-hint)",
    textAlign: "center" as const,
    marginTop: 3,
    width: 26,
  },
  analyticsDivider: { height: 1, background: "var(--border-dim)", margin: "24px 0" },
  statGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, marginBottom: 24 },
  statCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: "16px 18px",
  },
  statValue: {
    fontSize: 24,
    fontWeight: 700,
    color: "var(--text-primary)",
    lineHeight: 1.15,
    letterSpacing: -0.5,
  },
  statLabel: { marginTop: 4, fontSize: 11.5, color: "var(--text-muted)", fontWeight: 500 },
  analyticsRow: { display: "flex", flexDirection: "column", gap: 12 },
  analyticsCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-dim)",
    borderRadius: 12,
    padding: "16px 18px",
  },
  analyticsCardTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-secondary)",
    letterSpacing: 0.3,
    marginBottom: 14,
    textTransform: "uppercase" as const,
  },
  agentBarWrap: { display: "flex", flexDirection: "column", gap: 10 },
  agentBarRow: { display: "flex", flexDirection: "column", gap: 4 },
  agentBarMeta: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 12,
    color: "var(--text-secondary)",
    fontWeight: 500,
  },
  agentBarTrack: { height: 6, borderRadius: 3, background: "var(--bg-input)", overflow: "hidden" },
  agentBarFill: { height: "100%", borderRadius: 3, transition: "width 0.4s ease" },
  projectRankList: { display: "flex", flexDirection: "column", gap: 8 },
  projectRankRow: { display: "flex", alignItems: "center", gap: 10 },
  projectRankName: {
    flex: 1,
    fontSize: 13,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  projectRankCount: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)", flexShrink: 0 },
  errorBoundaryWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px",
    gap: 12,
    color: "var(--text-muted)",
    fontSize: 13,
    textAlign: "center" as const,
  },
  errorBoundaryIcon: { fontSize: 28, lineHeight: 1 },
  errorBoundaryTitle: { fontWeight: 600, color: "var(--text-secondary)" },
  errorBoundaryMessage: {
    maxWidth: 320,
    fontSize: 12,
    color: "var(--text-hint)",
    wordBreak: "break-word" as const,
    lineHeight: 1.5,
  },
  errorBoundaryActions: { display: "flex", gap: 8 },
  errorBoundaryBtn: {
    padding: "5px 16px",
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    color: "var(--text-secondary)",
    fontSize: 12,
    cursor: "pointer",
    marginTop: 4,
  },
} satisfies Record<string, React.CSSProperties>;
