import type React from "react";

export const panels = {
  newTaskOuter: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 48px",
    position: "relative",
    overflow: "visible",
  },
  newTaskHeader: { marginBottom: 20, textAlign: "center" },
  newTaskTitle: {
    display: "block",
    fontSize: 22,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  newTaskMeta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  metaChip: {
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    borderRadius: 4,
    padding: "2px 7px",
    fontSize: 12,
  },
  composeCard: {
    width: "100%",
    maxWidth: 700,
    background: "var(--bg-card)",
    border: "1.5px solid var(--accent)",
    borderRadius: 10,
    boxShadow: "0 0 0 3px var(--accent-subtle), var(--shadow-md)",
    overflow: "visible",
  },
  agentMissingMdBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    width: "100%",
    maxWidth: 700,
    marginBottom: 10,
    padding: "10px 14px",
    background: "rgba(234,179,8,0.10)",
    border: "1px solid rgba(234,179,8,0.30)",
    borderRadius: 8,
    boxSizing: "border-box" as const,
  },
  composeTextarea: {
    display: "block",
    width: "100%",
    padding: "16px 16px 8px",
    border: "none",
    outline: "none",
    resize: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 14,
    lineHeight: 1.65,
    fontFamily: "var(--font-ui)",
  },
  toolbar: {
    borderTop: "1px solid var(--border-dim)",
    padding: "8px 10px",
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "var(--bg-card)",
    borderRadius: "0 0 8px 8px",
  },
  toolbarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "5px 7px",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
  },
  toolbarDivider: {
    width: 1,
    height: 18,
    background: "var(--border-dim)",
    margin: "0 2px",
    flexShrink: 0,
  },
  toolbarBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 9px",
    background: "var(--bg-hover)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-primary)",
    cursor: "pointer",
  },
  saveTodoBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "6px 12px",
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    transition: "opacity 0.15s",
  },
  sendBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 14px",
    background: "var(--accent)",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  kbd: {
    fontSize: 10.5,
    opacity: 0.7,
    background: "rgba(255,255,255,0.15)",
    borderRadius: 3,
    padding: "1px 4px",
    fontFamily: "var(--font-ui)",
  },
  dropdownPanel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    zIndex: 100,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    boxShadow: "var(--shadow-md)",
    padding: 4,
    minWidth: 220,
  },
  dropdownOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    cursor: "pointer",
  },
  fileChipsRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 6,
    padding: "10px 14px 4px",
    borderBottom: "1px solid var(--border-dim)",
  },
  fileChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px 3px 7px",
    background: "var(--accent-subtle)",
    border: "1px solid color-mix(in srgb, var(--accent) 30%, transparent)",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--accent)",
    maxWidth: 240,
  },
  fileChipName: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  fileChipRemove: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    display: "flex",
    alignItems: "center",
    color: "var(--accent)",
    opacity: 0.6,
    marginLeft: 1,
    flexShrink: 0,
  },
  mentionDropdown: {
    position: "absolute" as const,
    bottom: "calc(100% + 6px)",
    left: 0,
    right: 0,
    zIndex: 200,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    boxShadow: "var(--shadow-lg, var(--shadow-md))",
    padding: 4,
    maxHeight: 260,
    overflowY: "auto" as const,
  },
  mentionOption: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionOptionName: { fontSize: 13, fontWeight: 500, color: "var(--text-primary)", flexShrink: 0 },
  mentionOptionDir: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  mentionSeparator: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 3px",
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-hint)",
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
    userSelect: "none" as const,
  },
  mentionProjectItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionCrossHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 5px",
    fontSize: 11.5,
    fontWeight: 500,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border-dim)",
    marginBottom: 3,
    userSelect: "none" as const,
  },
} satisfies Record<string, React.CSSProperties>;
