import type React from "react";

export const terminal = {
  runHeader: {
    padding: "16px 20px 8px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  cancelBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--border-medium)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  },
  resumeBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--control-active-fg)",
    borderRadius: 5,
    fontSize: 12,
    color: "var(--control-active-fg)",
    cursor: "pointer",
    flexShrink: 0,
  },
  terminalContainer: { flex: 1, overflow: "hidden" as const, padding: "14px 16px 16px" },
  codexComposerWrap: {
    flexShrink: 0,
    padding: "10px 16px 14px",
    borderTop: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  codexComposerBox: {
    display: "flex",
    alignItems: "flex-end",
    gap: 10,
    padding: "10px 10px 10px 12px",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-input)",
  },
  codexComposerInput: {
    flex: 1,
    minHeight: 38,
    maxHeight: 130,
    resize: "vertical" as const,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-sans)",
    fontSize: 13,
    lineHeight: 1.45,
  },
  codexComposerSend: {
    flexShrink: 0,
    height: 32,
    padding: "0 13px",
    border: "1px solid var(--control-active-fg)",
    borderRadius: 6,
    background: "var(--control-active-fg)",
    color: "var(--control-active-bg)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  codexComposerSendDisabled: {
    opacity: 0.45,
    cursor: "default",
  },
} satisfies Record<string, React.CSSProperties>;
